# Generated by Django 5.2.5 on 2025-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='info', max_length=20)),
                ('message', models.CharField(default='Waiting for scan...', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
