# Generated by Django 5.2.5 on 2025-08-17 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_latestscanstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestscanstatus',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
