# Generated by Django 5.2.5 on 2025-08-17 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_latestscanstatus_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 18, 40, 44, 615973, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='latestscanstatus',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 18, 40, 44, 616583, tzinfo=datetime.timezone.utc)),
        ),
    ]
