# Generated by Django 5.2.5 on 2025-08-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='latestscanstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
